//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class BookEntities : DbContext
    {
        public BookEntities()
            : base("name=BookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<Book> Books { get; set; }
    
        public virtual int CreatAdmin(string name, string pass)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreatAdmin", nameParameter, passParameter);
        }
    
        public virtual ObjectResult<GetAllUser_Result> GetAllUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllUser_Result>("GetAllUser");
        }
    
        public virtual ObjectResult<GetUser_Result> GetUser(string name, string pass)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUser_Result>("GetUser", nameParameter, passParameter);
        }
    
        public virtual int CreatMember(string name, string lastname, string phone, string nationalcode, string bookname)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var nationalcodeParameter = nationalcode != null ?
                new ObjectParameter("nationalcode", nationalcode) :
                new ObjectParameter("nationalcode", typeof(string));
    
            var booknameParameter = bookname != null ?
                new ObjectParameter("bookname", bookname) :
                new ObjectParameter("bookname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreatMember", nameParameter, lastnameParameter, phoneParameter, nationalcodeParameter, booknameParameter);
        }
    
        public virtual int CreatBook(string name, string author, string topic, string shelf, string num, string price)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var authorParameter = author != null ?
                new ObjectParameter("author", author) :
                new ObjectParameter("author", typeof(string));
    
            var topicParameter = topic != null ?
                new ObjectParameter("topic", topic) :
                new ObjectParameter("topic", typeof(string));
    
            var shelfParameter = shelf != null ?
                new ObjectParameter("shelf", shelf) :
                new ObjectParameter("shelf", typeof(string));
    
            var numParameter = num != null ?
                new ObjectParameter("num", num) :
                new ObjectParameter("num", typeof(string));
    
            var priceParameter = price != null ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreatBook", nameParameter, authorParameter, topicParameter, shelfParameter, numParameter, priceParameter);
        }
    
        public virtual ObjectResult<string> ListPrice()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ListPrice");
        }
    
        public virtual ObjectResult<ListPriceBook_Result> ListPriceBook()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListPriceBook_Result>("ListPriceBook");
        }
    
        public virtual ObjectResult<ListMember_Result> ListMember(string lastname, string nationalcode)
        {
            var lastnameParameter = lastname != null ?
                new ObjectParameter("lastname", lastname) :
                new ObjectParameter("lastname", typeof(string));
    
            var nationalcodeParameter = nationalcode != null ?
                new ObjectParameter("nationalcode", nationalcode) :
                new ObjectParameter("nationalcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListMember_Result>("ListMember", lastnameParameter, nationalcodeParameter);
        }
    
        public virtual ObjectResult<ListBook_Result> ListBook(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListBook_Result>("ListBook", nameParameter);
        }
    
        public virtual ObjectResult<ListSearchBook_Result> ListSearchBook(string name, string topic)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var topicParameter = topic != null ?
                new ObjectParameter("topic", topic) :
                new ObjectParameter("topic", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListSearchBook_Result>("ListSearchBook", nameParameter, topicParameter);
        }
    
        public virtual ObjectResult<ListTopic_Result> ListTopic(string topic)
        {
            var topicParameter = topic != null ?
                new ObjectParameter("topic", topic) :
                new ObjectParameter("topic", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListTopic_Result>("ListTopic", topicParameter);
        }
    
        public virtual ObjectResult<ListReport_Result> ListReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListReport_Result>("ListReport");
        }
    }
}
